### PR TITLE
Adapt to 33C3 Changes - now it works for me ( SCR )

### PR DESCRIPTION
**Pull request by ligi**
speaker field has changed and TrackName is currently not in there ( hence your test was failing )

### CODE REVIEW

**Comment by johnjohndoe** [comment]
All `@JsonProperty("speakers")` should be changed to `@JsonProperty("speaker_names")`.
Let's also add a property for the `language` attribute.

**Comment by ligi** [comment]
I replaced the other speakers with speaker_name - but will not do language - we should switch to moshi first #5

**Comment by johnjohndoe** [comment]
I added the `language` field myself and a few additional changes to make it working for 33C3.

**Comment by ligi** [comment]
great! can you please tag the latest master?

**Comment by johnjohndoe** [comment]
I would say try it out first and once it works for you I will release a new version.

**Comment by ligi** [comment]
just tried it out and it works

**Comment by johnjohndoe** [comment]
I also updated the [demo app](https://github.com/johnjohndoe/HalfnarpClientDemo).

**Comment by johnjohndoe** [comment]
v.3.0.0 is published.

**Pull request merged**
